- id: velka
  name: Velka Secret Scanner
  description: Scan staged files for leaked secrets and credentials
  entry: velka scan --staged --mortal-only
  language: rust
  types: [text]
  pass_filenames: false
